-- Generated by maps/labels/build_area_labels.py from WorldMapOverlay.db2
-- (Forever 1.60.1.70009). {areaID, x%, y%, w%, h%} per uiMapID; names come
-- from C_Map.GetAreaInfo at runtime so they follow the client locale.

local Nx = _G.Nx
if not Nx or not Nx.Map then return end

Nx.Map.AreaLabels = {
    [1411] = { -- Durotar
        { 370, 52.4, 24.7, 10.0, 13.5 }, -- Drygulch Ravine
        { 368, 65.4, 84.6, 11.0, 28.4 }, -- Echo Isles
        { 366, 48.9, 79.3, 6.0, 9.0 }, -- Kolkar Crag
        { 362, 54.6, 42.7, 9.5, 12.0 }, -- Razor Hill
        { 816, 41.2, 43.4, 12.5, 18.0 }, -- Razormane Grounds
        { 367, 56.1, 73.0, 7.5, 11.2 }, -- Sen'jin Village
        { 817, 53.6, 12.0, 7.5, 7.5 }, -- Skull Rock
        { 369, 40.7, 24.3, 10.5, 17.2 }, -- Thunder Ridge
        { 372, 57.6, 56.1, 8.5, 15.0 }, -- Tiragarde Keep
        { 363, 44.4, 67.0, 10.0, 15.7 }, -- Valley of Trials
    },
    [1412] = { -- Mulgore
        { 404, 32.6, 50.7, 9.3, 9.0 }, -- Bael'dun Digsite
        { 222, 47.0, 62.4, 7.3, 8.5 }, -- Bloodhoof Village
        { 358, 61.4, 80.8, 13.8, 13.3 }, -- Brambleblade Ravine
        { 818, 34.1, 68.5, 6.2, 10.0 }, -- Palemane Rock
        { 224, 52.0, 52.6, 4.9, 6.1 }, -- Ravaged Caravan
        { 220, 46.7, 82.9, 16.3, 13.0 }, -- Red Cloud Mesa
        { 225, 57.8, 31.6, 8.6, 12.9 }, -- Red Rocks
        { 820, 49.5, 39.8, 7.7, 18.9 }, -- The Golden Plains
        { 821, 60.4, 68.1, 11.3, 9.9 }, -- The Rolling Plains
        { 360, 59.2, 52.1, 6.9, 9.9 }, -- The Venture Co. Mine
        { 397, 44.4, 50.0, 5.6, 6.6 }, -- Thunderhorn Water Well
        { 398, 42.6, 24.3, 5.5, 7.3 }, -- Wildmane Water Well
        { 819, 50.6, 20.5, 10.7, 10.8 }, -- Windfury Ridge
        { 396, 51.9, 68.9, 3.8, 6.9 }, -- Winterhoof Water Well
    },
    [1413] = { -- The Barrens
        { 1700, 43.2, 48.3, 8.5, 14.2 }, -- Agama'gor
        { 359, 47.7, 83.8, 5.5, 9.0 }, -- Bael Modan
        { 1701, 41.7, 79.0, 6.5, 11.2 }, -- Blackthorn Ridge
        { 381, 61.9, 6.7, 5.0, 10.5 }, -- Boulder Lode Mine
        { 1698, 50.6, 58.4, 4.5, 10.5 }, -- Bramblescar
        { 378, 45.7, 61.0, 6.5, 8.2 }, -- Camp Taurajo
        { 384, 48.4, 18.3, 7.0, 8.2 }, -- Dreadmist Peak
        { 379, 61.1, 21.3, 4.5, 8.2 }, -- Far Watch Post
        { 390, 46.2, 70.7, 7.5, 8.2 }, -- Field of Giants
        { 1704, 55.6, 19.1, 5.5, 6.7 }, -- Grol'dom Farm
        { 1702, 37.4, 28.4, 8.0, 10.5 }, -- Honor's Stand
        { 387, 46.7, 38.9, 6.5, 10.5 }, -- Lushwater Oasis
        { 385, 61.1, 55.4, 7.5, 9.0 }, -- Northwatch Hold
        { 1697, 55.9, 51.3, 6.0, 6.7 }, -- Raptor Grounds
        { 392, 62.6, 37.4, 5.5, 7.5 }, -- Ratchet
        { 1316, 48.9, 91.7, 9.0, 9.7 }, -- Razorfen Downs
        { 1717, 40.9, 88.3, 8.0, 10.5 }, -- Razorfen Kraul
        { 380, 51.6, 28.4, 6.5, 7.5 }, -- The Crossroads
        { 383, 39.7, 14.6, 9.5, 11.2 }, -- The Dry Hills
        { 386, 45.4, 23.6, 7.0, 9.7 }, -- The Forgotten Pools
        { 391, 63.6, 45.3, 4.5, 9.7 }, -- The Merchant Coast
        { 1703, 47.9, 6.7, 8.0, 9.0 }, -- The Mor'shan Rampart
        { 382, 55.4, 7.5, 10.0, 9.0 }, -- The Sludge Fen
        { 388, 55.6, 42.7, 5.5, 9.0 }, -- The Stagnant Oasis
        { 1699, 56.9, 28.4, 6.0, 7.5 }, -- Thorn Hill
    },
    [1416] = { -- Alterac Mountains
        { 1684, 82.1, 66.6, 18.5, 34.4 }, -- Chillwind Point
        { 1679, 48.2, 83.8, 9.5, 19.5 }, -- Corrahn's Dagger
        { 282, 48.4, 41.9, 10.0, 19.5 }, -- Crushridge Hold
        { 279, 15.2, 65.9, 15.5, 24.0 }, -- Dalaran
        { 1682, 40.4, 17.2, 7.0, 13.5 }, -- Dandred's Fold
        { 1357, 50.1, 58.8, 8.5, 11.2 }, -- Gallows' Corner
        { 1677, 30.7, 85.7, 7.5, 14.2 }, -- Gavin's Naze
        { 1683, 39.7, 69.2, 10.5, 12.7 }, -- Growless Cave
        { 278, 20.5, 85.0, 9.0, 12.7 }, -- Lordamere Internment Camp
        { 1681, 28.2, 37.8, 12.5, 18.7 }, -- Misty Shore
        { 281, 39.9, 53.5, 14.0, 18.7 }, -- Ruins of Alterac
        { 1678, 58.4, 68.9, 9.0, 13.5 }, -- Sofera's Naze
        { 280, 63.4, 45.3, 13.0, 14.2 }, -- Strahnbrad
        { 1680, 38.9, 90.2, 9.0, 17.2 }, -- The Headland
        { 284, 56.4, 27.3, 13.0, 18.7 }, -- The Uplands
    },
    [1417] = { -- Arathi Highlands
        { 1858, 37.7, 41.5, 5.5, 18.7 }, -- Boulder'gor
        { 316, 54.1, 73.7, 13.5, 20.2 }, -- Boulderfist Hall
        { 333, 63.6, 34.1, 8.5, 15.7 }, -- Circle of East Binding
        { 335, 36.7, 61.8, 10.5, 14.2 }, -- Circle of Inner Binding
        { 336, 52.6, 52.8, 8.5, 9.7 }, -- Circle of Outer Binding
        { 334, 22.2, 25.4, 10.5, 18.0 }, -- Circle of West Binding
        { 315, 55.1, 39.7, 9.5, 10.5 }, -- Dabyrie's Farmstead
        { 327, 30.9, 79.7, 19.0, 17.2 }, -- Faldir's Cove
        { 314, 61.4, 56.5, 8.0, 11.2 }, -- Go'Shek Farm
        { 321, 75.1, 36.7, 12.5, 16.5 }, -- Hammerfall
        { 313, 31.7, 31.4, 8.5, 18.0 }, -- Northfold Manor
        { 320, 45.9, 47.2, 8.0, 16.5 }, -- Refuge Pointe
        { 324, 22.7, 62.1, 17.5, 22.5 }, -- Stromgarde Keep
        { 880, 45.9, 83.1, 12.0, 21.0 }, -- Thandol Span
        { 1857, 17.7, 37.8, 10.5, 21.7 }, -- Thoradin's Wall
        { 317, 66.6, 67.0, 14.5, 11.2 }, -- Witherbark Village
    },
    [1418] = { -- Badlands
        { 345, 47.2, 74.1, 14.5, 22.5 }, -- Agmond's End
        { 338, 42.9, 33.3, 14.0, 15.7 }, -- Angor Fortress
        { 337, 15.7, 61.8, 11.5, 15.7 }, -- Apocryphan's Rest
        { 342, 61.4, 72.6, 14.0, 25.4 }, -- Camp Boff
        { 344, 13.2, 81.6, 18.5, 21.0 }, -- Camp Cagg
        { 341, 66.1, 22.5, 12.5, 15.0 }, -- Camp Kosh
        { 1898, 62.6, 46.0, 12.5, 18.7 }, -- Dustwind Gulch
        { 346, 56.6, 36.3, 13.5, 15.7 }, -- Hammertoe's Digsite
        { 340, 8.7, 47.5, 15.5, 15.7 }, -- Kargath
        { 339, 78.3, 50.9, 20.0, 34.4 }, -- Lethlor Ravine
        { 1879, 30.7, 75.2, 18.5, 24.7 }, -- Mirage Flats
        { 1878, 30.4, 51.6, 17.0, 21.0 }, -- The Dustbowl
        { 1897, 49.2, 16.5, 18.5, 18.0 }, -- The Maker's Terrace
        { 1877, 46.4, 56.9, 13.0, 18.0 }, -- Valley of Fangs
    },
    [1419] = { -- Blasted Lands
        { 1441, 39.7, 31.8, 6.5, 9.7 }, -- Altar of Storms
        { 1437, 43.2, 14.2, 9.5, 9.0 }, -- Dreadmaul Hold
        { 1439, 50.4, 44.2, 11.0, 12.0 }, -- Dreadmaul Post
        { 1457, 55.9, 13.8, 8.0, 8.2 }, -- Garrison Armory
        { 1438, 64.4, 18.3, 10.0, 11.2 }, -- Nethergarde Keep
        { 2517, 48.7, 29.9, 8.5, 12.0 }, -- Rise of the Defiler
        { 1440, 62.9, 33.3, 11.0, 9.7 }, -- Serpent's Coil
        { 72, 58.4, 56.5, 13.0, 15.7 }, -- The Dark Portal
        { 73, 37.9, 62.5, 23.0, 36.7 }, -- The Tainted Scar
    },
    [1420] = { -- Tirisfal Glades
        { 157, 45.2, 36.4, 13.8, 18.0 }, -- Agamand Mills
        { 165, 72.8, 61.7, 13.1, 23.1 }, -- Balnir Farmstead
        { 162, 68.3, 42.1, 10.2, 34.9 }, -- Brightwater Lake
        { 159, 59.6, 55.2, 7.5, 14.7 }, -- Brill
        { 166, 53.7, 60.0, 7.3, 10.6 }, -- Cold Hearth Manor
        { 167, 77.9, 51.4, 14.5, 15.4 }, -- Crusader Outpost
        { 154, 34.4, 63.9, 13.2, 18.3 }, -- Deathknell
        { 164, 57.8, 38.2, 9.6, 21.9 }, -- Garren's Haunt
        { 811, 47.3, 66.3, 14.6, 14.1 }, -- Nightmare Vale
        { 459, 77.8, 32.9, 8.0, 31.6 }, -- Scarlet Watch Post
        { 156, 36.0, 49.5, 15.3, 12.1 }, -- Solliden Farmstead
        { 810, 48.0, 51.3, 10.3, 10.6 }, -- Stillwater Pond
        { 152, 83.6, 69.6, 13.5, 25.4 }, -- The Bulwark
        { 812, 87.2, 48.5, 19.3, 25.1 }, -- Venomweb Vale
    },
    [1421] = { -- Silverpine Forest
        { 233, 63.4, 62.9, 11.0, 15.0 }, -- Ambermill
        { 231, 58.9, 72.2, 8.0, 9.7 }, -- Beren's Peril
        { 213, 56.1, 48.3, 6.5, 11.2 }, -- Deep Elem Mine
        { 172, 71.9, 28.8, 19.0, 20.2 }, -- Fenris Isle
        { 238, 56.6, 10.5, 6.5, 6.0 }, -- Malden's Orchard
        { 928, 40.4, 28.4, 8.0, 9.0 }, -- North Tide's Hollow
        { 229, 46.9, 53.9, 8.0, 9.0 }, -- Olsen's Farthing
        { 204, 44.9, 73.7, 8.0, 8.2 }, -- Pyrewood Village
        { 236, 44.2, 66.2, 10.5, 9.7 }, -- Shadowfang Keep
        { 240, 46.4, 21.7, 7.0, 9.0 }, -- The Dead Field
        { 237, 55.4, 36.3, 9.0, 11.2 }, -- The Decrepit Ferry
        { 230, 46.4, 86.1, 9.0, 13.5 }, -- The Greymane Wall
        { 228, 44.7, 40.8, 8.5, 9.7 }, -- The Sepulcher
        { 927, 54.1, 22.8, 6.5, 11.2 }, -- The Shining Strand
        { 226, 37.4, 15.7, 10.0, 10.5 }, -- The Skittering Dark
    },
    [1422] = { -- Western Plaguelands
        { 2298, 68.9, 75.2, 10.0, 14.2 }, -- Caer Darrow
        { 200, 46.4, 52.8, 9.0, 11.2 }, -- Dalson's Tears
        { 2297, 68.4, 73.7, 25.9, 24.7 }, -- Darrowmere Lake
        { 199, 37.4, 55.8, 8.0, 9.7 }, -- Felstone Field
        { 201, 62.9, 57.3, 10.0, 11.2 }, -- Gahrron's Withering
        { 190, 47.2, 18.0, 21.5, 19.5 }, -- Hearthglen
        { 192, 47.4, 36.3, 10.0, 14.2 }, -- Northridge Lumber Camp
        { 193, 43.7, 69.2, 11.5, 12.7 }, -- Ruins of Andorhal
        { 197, 51.6, 79.3, 9.5, 13.5 }, -- Sorrow Hill
        { 813, 26.4, 58.0, 12.0, 11.2 }, -- The Bulwark
        { 198, 65.1, 42.3, 7.5, 12.7 }, -- The Weeping Cave
        { 202, 53.4, 65.5, 7.0, 9.7 }, -- The Writhing Haunt
        { 2620, 67.6, 38.5, 10.5, 41.2 }, -- Thondroril River
    },
    [1423] = { -- Eastern Plaguelands
        { 2624, 51.9, 49.8, 9.0, 12.7 }, -- Blackwood Lake
        { 2264, 59.6, 70.4, 9.5, 12.0 }, -- Corin's Crossing
        { 2263, 38.7, 75.6, 8.5, 12.0 }, -- Crown Guard Tower
        { 2262, 39.9, 89.8, 12.0, 12.0 }, -- Darrowshire
        { 2271, 67.9, 49.8, 7.0, 12.7 }, -- Eastwall Tower
        { 2621, 62.6, 80.1, 12.5, 13.5 }, -- Lake Mereldar
        { 2268, 82.1, 58.4, 7.5, 12.0 }, -- Light's Hope Chapel
        { 2272, 70.6, 31.8, 8.5, 12.7 }, -- Northdale
        { 2275, 57.9, 28.4, 13.0, 13.5 }, -- Northpass Tower
        { 2622, 74.1, 62.5, 9.5, 18.7 }, -- Pestilent Scar
        { 2277, 36.4, 33.7, 25.9, 19.5 }, -- Plaguewood
        { 2276, 52.9, 16.5, 9.0, 9.0 }, -- Quel'Lithien Lodge
        { 2279, 31.2, 15.3, 13.5, 20.2 }, -- Stratholme
        { 2627, 17.7, 32.2, 12.5, 10.5 }, -- Terrordale
        { 2258, 40.4, 52.0, 10.0, 14.2 }, -- The Fungal Vale
        { 2623, 52.6, 66.6, 10.5, 12.0 }, -- The Infectis Scar
        { 2260, 26.7, 73.4, 10.5, 10.5 }, -- The Marris Stead
        { 2270, 84.3, 41.5, 12.0, 15.7 }, -- The Noxious Glade
        { 2261, 28.4, 84.6, 8.0, 13.5 }, -- The Undercroft
        { 2619, 7.7, 60.3, 10.5, 44.2 }, -- Thondroril River
        { 2266, 84.8, 83.1, 17.0, 15.0 }, -- Tyr's Hand
        { 2273, 73.1, 14.6, 12.5, 11.2 }, -- Zul'Mashar
    },
    [1424] = { -- Hillsbrad Foothills
        { 288, 26.2, 57.3, 9.5, 11.2 }, -- Azurelode Mine
        { 1056, 50.9, 33.7, 15.0, 10.5 }, -- Darrow Hill
        { 290, 72.1, 71.5, 9.5, 21.7 }, -- Dun Garok
        { 275, 76.8, 40.8, 13.0, 15.7 }, -- Durnholde Keep
        { 294, 61.9, 74.5, 14.0, 17.2 }, -- Eastern Strand
        { 286, 34.9, 44.9, 20.0, 29.9 }, -- Hillsbrad Fields
        { 289, 63.9, 55.4, 12.0, 24.0 }, -- Nethander Stead
        { 896, 17.2, 79.7, 12.5, 15.7 }, -- Purgation Isle
        { 285, 15.5, 46.0, 16.0, 18.7 }, -- Southpoint Tower
        { 271, 49.7, 55.4, 10.5, 18.0 }, -- Southshore
        { 272, 61.1, 25.8, 13.5, 21.7 }, -- Tarren Mill
        { 295, 35.7, 68.1, 23.5, 12.0 }, -- Western Strand
    },
    [1425] = { -- The Hinterlands
        { 348, 14.7, 50.5, 12.5, 15.7 }, -- Aerie Peak
        { 1884, 49.7, 37.1, 11.5, 12.7 }, -- Agol'watha
        { 1885, 28.2, 61.8, 10.5, 14.2 }, -- Hiri'watha
        { 354, 62.4, 69.6, 15.0, 31.4 }, -- Jintha'Alor
        { 1882, 22.7, 38.2, 7.5, 22.5 }, -- Plaguemist Ravine
        { 350, 31.4, 43.0, 12.0, 18.7 }, -- Quel'Danil Lodge
        { 356, 64.1, 25.4, 16.5, 24.0 }, -- Seradane
        { 353, 34.7, 71.5, 10.5, 14.2 }, -- Shadra'Alor
        { 1917, 70.1, 50.5, 13.5, 15.7 }, -- Shaol'watha
        { 351, 59.1, 43.0, 8.5, 11.2 }, -- Skulk Rock
        { 355, 48.7, 66.2, 9.5, 11.2 }, -- The Altar of Zul
        { 1886, 50.1, 53.5, 9.5, 12.7 }, -- The Creeping Ruin
        { 307, 79.3, 68.9, 8.0, 32.9 }, -- The Overlook Cliffs
        { 1883, 40.2, 58.4, 7.5, 10.5 }, -- Valorwind Lake
    },
    [1426] = { -- Dun Morogh
        { 803, 63.4, 50.5, 6.0, 6.7 }, -- Amberstill Ranch
        { 137, 30.4, 46.0, 5.0, 9.7 }, -- Brewnall Village
        { 801, 35.9, 53.1, 8.0, 10.5 }, -- Chill Breeze Valley
        { 800, 34.9, 68.1, 6.0, 10.5 }, -- Coldridge Pass
        { 135, 28.2, 51.6, 4.5, 9.0 }, -- Frostmane Hold
        { 133, 24.2, 38.2, 7.5, 12.0 }, -- Gnomeregan
        { 134, 68.6, 57.6, 9.5, 13.5 }, -- Gol'Bolar Quarry
        { 212, 76.8, 54.3, 8.0, 14.2 }, -- Helm's Bed Lake
        { 211, 34.9, 38.5, 7.0, 18.7 }, -- Iceflow Lake
        { 138, 57.4, 42.7, 6.0, 12.0 }, -- Misty Pine Refuge
        { 808, 82.8, 37.8, 6.0, 14.2 }, -- North Gate Outpost
        { 802, 40.9, 40.0, 6.0, 14.2 }, -- Shimmer Ridge
        { 806, 85.3, 50.9, 6.0, 10.5 }, -- South Gate Outpost
        { 136, 40.9, 58.0, 6.0, 11.2 }, -- The Grizzled Den
        { 804, 59.9, 57.3, 9.0, 8.2 }, -- The Tundrid Hills
    },
    [1427] = { -- Searing Gorge
        { 1957, 23.0, 73.4, 15.0, 22.5 }, -- Blackchar Cave
        { 1959, 67.4, 29.2, 28.9, 40.4 }, -- Dustfire Valley
        { 1442, 27.9, 33.7, 24.0, 28.4 }, -- Firewatch Ridge
        { 247, 64.9, 58.8, 18.0, 14.2 }, -- Grimesilt Dig Site
        { 1958, 69.4, 76.3, 18.0, 21.0 }, -- Tanner Camp
        { 246, 46.2, 49.4, 29.4, 21.0 }, -- The Cauldron
        { 1444, 44.9, 84.2, 24.0, 30.7 }, -- The Sea of Cinders
    },
    [1428] = { -- Burning Steppes
        { 255, 15.7, 32.2, 11.5, 19.5 }, -- Altar of Storms
        { 254, 29.9, 31.8, 16.0, 20.2 }, -- Blackrock Mountain
        { 2417, 75.1, 68.5, 14.5, 21.7 }, -- Blackrock Pass
        { 252, 43.7, 35.2, 13.5, 22.5 }, -- Blackrock Stronghold
        { 2421, 27.9, 65.5, 30.9, 32.2 }, -- Draco'dar
        { 249, 81.3, 41.5, 14.0, 21.7 }, -- Dreadmaul Rock
        { 2418, 88.6, 64.7, 16.5, 24.7 }, -- Morgan's Vigil
        { 250, 65.1, 34.4, 20.5, 25.4 }, -- Ruins of Thaurissan
        { 2420, 88.6, 35.9, 21.5, 37.4 }, -- Terror Wing Path
        { 253, 50.1, 56.5, 17.5, 15.7 }, -- The Pillar of Ash
    },
    [1429] = { -- Elwynn Forest
        { 62, 67.4, 79.3, 12.0, 10.5 }, -- Brackwell Pumpkin Patch
        { 18, 52.6, 64.0, 15.5, 14.2 }, -- Crystal Lake
        { 88, 83.6, 66.2, 12.5, 12.7 }, -- Eastvale Logging Camp
        { 57, 38.4, 84.2, 17.0, 15.7 }, -- Fargodeep Mine
        { 60, 25.0, 81.6, 10.0, 29.9 }, -- Forest's Edge
        { 87, 41.2, 64.7, 8.5, 9.7 }, -- Goldshire
        { 797, 53.6, 83.1, 15.5, 18.0 }, -- Jerod's Landing
        { 9, 51.1, 42.3, 17.5, 27.7 }, -- Northshire Valley
        { 798, 85.1, 80.5, 12.5, 9.7 }, -- Ridgepoint Tower
        { 86, 75.1, 49.8, 15.5, 24.7 }, -- Stone Cairn Lake
        { 91, 67.6, 66.6, 13.5, 13.5 }, -- Tower of Azora
    },
    [1430] = { -- Deadwind Pass
        { 2697, 45.2, 35.9, 27.4, 34.4 }, -- Deadman's Crossing
        { 2562, 42.7, 68.9, 18.5, 24.0 }, -- Karazhan
        { 2561, 58.6, 64.7, 15.5, 32.2 }, -- The Vice
    },
    [1431] = { -- Duskwood
        { 536, 21.7, 69.2, 11.5, 14.2 }, -- Addle's Stead
        { 242, 62.6, 40.8, 11.5, 32.2 }, -- Brightwood Grove
        { 42, 77.1, 44.9, 12.5, 15.0 }, -- Darkshire
        { 1098, 74.4, 33.7, 10.0, 9.0 }, -- Manor Mistmantle
        { 94, 20.7, 56.1, 10.5, 10.5 }, -- Raven Hill
        { 492, 20.2, 41.9, 11.5, 21.0 }, -- Raven Hill Cemetery
        { 799, 54.6, 21.3, 84.3, 17.2 }, -- The Darkened Bank
        { 1097, 10.0, 44.5, 8.9, 31.7 }, -- The Hushed Bank
        { 241, 64.1, 73.0, 12.5, 17.2 }, -- The Rotting Orchard
        { 245, 49.2, 73.4, 9.5, 15.0 }, -- The Yorgen Farmstead
        { 121, 80.1, 70.0, 9.5, 11.2 }, -- Tranquil Gardens Cemetery
        { 856, 47.7, 40.4, 21.5, 37.4 }, -- Twilight Grove
        { 93, 36.2, 73.4, 15.5, 16.5 }, -- Vul'Gol Ogre Mound
    },
    [1432] = { -- Loch Modan
        { 936, 45.2, 68.9, 11.5, 19.5 }, -- Grizzlepaw Ridge
        { 142, 69.4, 65.5, 14.0, 17.2 }, -- Ironband's Excavation Site
        { 143, 70.9, 25.1, 18.0, 18.7 }, -- Mo'grosh Stronghold
        { 838, 22.5, 15.3, 13.0, 17.2 }, -- North Gate Pass
        { 149, 34.4, 21.7, 11.0, 16.5 }, -- Silver Stream Mine
        { 923, 34.9, 77.8, 15.0, 26.9 }, -- Stonesplinter Valley
        { 146, 47.9, 12.7, 20.0, 12.0 }, -- Stonewrought Dam
        { 147, 83.1, 62.9, 8.5, 12.0 }, -- The Farstrider Lodge
        { 556, 50.1, 42.3, 19.5, 50.1 }, -- The Loch
        { 144, 34.9, 46.0, 10.0, 12.7 }, -- Thelsamar
        { 924, 20.5, 73.7, 11.0, 27.7 }, -- Valley of Kings
    },
    [1433] = { -- Redridge Mountains
        { 97, 47.9, 42.7, 13.9, 15.6 }, -- Alther's Mill
        { 1000, 71.1, 42.0, 17.2, 21.7 }, -- Galardell Valley
        { 68, 42.0, 59.8, 23.8, 18.4 }, -- Lake Everstill
        { 1001, 37.3, 76.9, 30.8, 16.5 }, -- Lakeridge Highway
        { 69, 21.4, 45.3, 24.0, 11.8 }, -- Lakeshire
        { 95, 23.4, 28.7, 23.4, 18.1 }, -- Redridge Canyons
        { 996, 34.1, 14.7, 13.3, 13.5 }, -- Render's Camp
        { 997, 70.4, 79.1, 22.3, 15.7 }, -- Render's Valley
        { 70, 62.3, 56.9, 10.6, 12.6 }, -- Stonewatch
        { 71, 73.2, 67.2, 16.2, 12.6 }, -- Stonewatch Falls
        { 1002, 11.9, 73.3, 13.3, 19.6 }, -- Three Corners
    },
    [1434] = { -- Stranglethorn Vale
        { 123, 29.4, 19.8, 5.0, 5.2 }, -- Bal'lal Ruins
        { 127, 41.7, 31.1, 5.5, 6.7 }, -- Balia'mah Ruins
        { 1739, 26.9, 53.5, 10.0, 9.7 }, -- Bloodsail Compound
        { 35, 26.2, 74.1, 8.5, 10.5 }, -- Booty Bay
        { 310, 40.9, 50.5, 6.0, 8.2 }, -- Crystalvein Mine
        { 117, 31.7, 27.3, 6.5, 6.7 }, -- Grom'gol Base Camp
        { 1741, 29.4, 44.2, 9.0, 12.0 }, -- Gurubashi Arena
        { 297, 38.9, 82.3, 8.0, 12.0 }, -- Jaguero Isle
        { 125, 34.4, 21.0, 5.0, 6.0 }, -- Kal'ai Ruins
        { 101, 45.4, 9.4, 8.0, 8.2 }, -- Kurzen's Compound
        { 37, 40.4, 18.7, 6.0, 7.5 }, -- Lake Nazferiti
        { 1737, 33.7, 64.4, 3.5, 10.5 }, -- Mistvale Valley
        { 129, 36.9, 29.6, 4.0, 5.2 }, -- Mizjah Ruins
        { 105, 49.4, 29.9, 8.0, 12.0 }, -- Mosh'Ogg Ogre Mound
        { 1738, 25.7, 62.5, 5.5, 9.7 }, -- Nek'mani Wellspring
        { 100, 34.2, 13.1, 7.5, 8.2 }, -- Nesingwary's Expedition
        { 99, 37.4, 5.6, 8.0, 5.2 }, -- Rebel Camp
        { 311, 39.7, 59.1, 4.5, 6.0 }, -- Ruins of Aboraz
        { 477, 35.7, 51.6, 4.5, 6.0 }, -- Ruins of Jubuwal
        { 102, 25.9, 12.4, 8.0, 8.2 }, -- Ruins of Zul'Kunda
        { 103, 46.7, 42.3, 6.5, 9.7 }, -- Ruins of Zul'Mamwe
        { 104, 24.2, 27.7, 12.5, 15.0 }, -- The Vile Reef
        { 1740, 44.2, 19.8, 4.5, 9.7 }, -- Venture Co. Base Camp
        { 43, 32.4, 79.3, 5.0, 7.5 }, -- Wild Shore
        { 128, 40.7, 41.2, 4.5, 12.0 }, -- Ziata'jai Ruins
        { 19, 59.9, 18.7, 15.0, 22.5 }, -- Zul'Gurub
        { 122, 21.2, 15.0, 4.5, 6.0 }, -- Zuuldaia Ruins
    },
    [1435] = { -- Swamp of Sorrows
        { 76, 65.1, 22.5, 22.5, 26.9 }, -- Fallow Sanctuary
        { 1777, 15.0, 62.9, 10.0, 21.0 }, -- Itharius's Cave
        { 300, 88.3, 52.8, 14.0, 83.1 }, -- Misty Reed Strand
        { 116, 13.2, 35.9, 16.5, 15.0 }, -- Misty Valley
        { 74, 71.1, 52.8, 18.5, 26.2 }, -- Pool of Tears
        { 1778, 83.8, 46.4, 13.0, 40.4 }, -- Sorrowmurk
        { 1780, 24.5, 52.4, 19.0, 18.0 }, -- Splinterspear Junction
        { 1797, 70.4, 79.0, 18.0, 21.7 }, -- Stagalbog
        { 75, 47.7, 55.0, 21.5, 20.2 }, -- Stonard
        { 657, 27.7, 35.9, 12.5, 15.0 }, -- The Harborage
        { 1798, 43.9, 34.8, 24.0, 21.7 }, -- The Shifting Mire
    },
    [1436] = { -- Westfall
        { 219, 38.2, 52.4, 11.5, 16.5 }, -- Alexston Farmstead
        { 921, 31.2, 69.6, 10.5, 13.5 }, -- Demont's Place
        { 109, 50.9, 21.3, 9.0, 12.7 }, -- Furlbrow's Pumpkin Farm
        { 113, 31.4, 41.5, 12.0, 14.2 }, -- Gold Coast Quarry
        { 111, 44.7, 24.3, 8.5, 11.2 }, -- Jangolode Mine
        { 20, 44.2, 65.5, 10.5, 20.2 }, -- Moonbrook
        { 107, 55.4, 32.6, 10.0, 11.2 }, -- Saldean's Farm
        { 108, 55.9, 49.8, 9.0, 15.7 }, -- Sentinel Hill
        { 920, 46.9, 79.0, 18.0, 11.2 }, -- The Dagger Hills
        { 917, 62.4, 61.4, 10.0, 12.0 }, -- The Dead Acre
        { 922, 63.4, 72.6, 15.0, 10.5 }, -- The Dust Plains
        { 916, 56.6, 17.6, 9.5, 12.7 }, -- The Jansen Stead
        { 918, 44.9, 36.3, 11.0, 12.7 }, -- The Molsen Farm
        { 115, 31.9, 86.1, 12.0, 13.5 }, -- Westfall Lighthouse
    },
    [1437] = { -- Wetlands
        { 1036, 47.4, 48.3, 15.0, 15.7 }, -- Angerfang Encampment
        { 1018, 20.0, 49.0, 15.0, 12.7 }, -- Black Channel Marsh
        { 1022, 19.2, 36.3, 14.5, 11.2 }, -- Bluegill Marsh
        { 1016, 60.6, 32.6, 11.5, 20.2 }, -- Direforge Hill
        { 205, 49.4, 16.8, 10.0, 9.7 }, -- Dun Modr
        { 309, 44.7, 31.1, 12.5, 17.2 }, -- Ironbeard's Tomb
        { 150, 10.2, 56.9, 6.5, 10.5 }, -- Menethil Harbor
        { 1020, 61.9, 54.6, 11.0, 18.0 }, -- Mosshide Fen
        { 1017, 72.1, 38.2, 11.5, 13.5 }, -- Raptor Ridge
        { 1023, 34.2, 24.3, 13.5, 20.2 }, -- Saltspray Glen
        { 1024, 23.2, 28.4, 18.5, 15.0 }, -- Sundown Marsh
        { 1025, 53.6, 36.7, 10.5, 22.5 }, -- The Green Belt
        { 1021, 56.4, 68.9, 12.0, 16.5 }, -- Thelgen Rock
        { 118, 35.9, 49.0, 10.0, 9.7 }, -- Whelgar's Excavation Site
    },
    [1438] = { -- Teldrassil
        { 736, 46.4, 57.3, 9.0, 23.2 }, -- Ban'ethil Hollow
        { 186, 55.1, 56.9, 11.5, 12.0 }, -- Dolanaar
        { 261, 43.9, 74.9, 8.0, 10.5 }, -- Gnarlpine Hold
        { 259, 57.6, 71.1, 16.5, 15.0 }, -- Lake Al'Ameth
        { 478, 40.4, 63.6, 6.0, 13.5 }, -- Pools of Arlithrien
        { 702, 55.6, 90.9, 1.5, 2.2 }, -- Rut'theran Village
        { 188, 59.6, 40.0, 12.5, 18.7 }, -- Shadowglen
        { 260, 65.6, 57.6, 10.5, 12.0 }, -- Starbreeze Village
        { 264, 37.9, 36.3, 6.0, 21.7 }, -- The Oracle Glade
        { 266, 46.9, 35.6, 11.0, 21.7 }, -- Wellspring Lake
    },
    [1439] = { -- Darkshore
        { 447, 42.7, 57.6, 6.5, 10.5 }, -- Ameth'Aran
        { 442, 39.2, 43.8, 7.5, 11.2 }, -- Auberdine
        { 446, 44.9, 36.3, 7.0, 8.2 }, -- Bashal'Aran
        { 456, 53.6, 33.3, 10.5, 9.7 }, -- Cliffspring River
        { 448, 42.9, 77.1, 9.0, 12.0 }, -- Grove of the Ancients
        { 450, 34.9, 85.3, 6.0, 9.0 }, -- Remtravel's Excavation
        { 443, 58.6, 16.5, 6.5, 15.0 }, -- Ruins of Mathystra
        { 449, 41.4, 88.7, 9.0, 11.2 }, -- The Master's Glaive
        { 444, 56.4, 26.2, 9.0, 9.0 }, -- Tower of Althalaxx
    },
    [1440] = { -- Ashenvale
        { 415, 37.2, 51.6, 12.5, 15.0 }, -- Astranaar
        { 438, 93.8, 36.3, 9.0, 12.7 }, -- Bough Shadow
        { 422, 69.1, 82.0, 11.5, 12.7 }, -- Fallen Sky Lake
        { 434, 83.1, 77.5, 16.5, 15.7 }, -- Felfire Hill
        { 417, 26.7, 63.6, 6.5, 10.5 }, -- Fire Scar Shrine
        { 424, 46.4, 46.8, 7.0, 11.2 }, -- Iris Lake
        { 441, 20.5, 40.4, 6.0, 12.0 }, -- Lake Falathim
        { 413, 29.2, 25.8, 8.5, 24.7 }, -- Maestra's Post
        { 421, 49.4, 73.4, 15.0, 18.0 }, -- Mystral Lake
        { 428, 71.6, 59.1, 11.5, 16.5 }, -- Night Run
        { 426, 60.9, 51.6, 10.0, 12.0 }, -- Raynewood Retreat
        { 430, 81.8, 48.3, 14.0, 9.7 }, -- Satyrnaar
        { 419, 56.1, 37.1, 12.5, 14.2 }, -- The Howling Vale
        { 418, 33.4, 67.4, 8.0, 13.5 }, -- The Ruins of Stardust
        { 416, 22.2, 52.8, 9.5, 14.2 }, -- The Shrine of Aessina
        { 414, 13.0, 22.1, 17.0, 26.2 }, -- The Zoram Strand
        { 2301, 36.9, 36.7, 7.0, 9.0 }, -- Thistlefur Village
        { 437, 91.1, 59.1, 11.5, 12.0 }, -- Warsong Lumber Camp
    },
    [1441] = { -- Thousand Needles
        { 480, 16.2, 17.6, 19.5, 23.2 }, -- Camp E'thok
        { 2097, 34.9, 36.3, 9.0, 15.7 }, -- Darkcloud Pinnacle
        { 484, 46.2, 52.8, 12.5, 15.7 }, -- Freewind Post
        { 482, 13.5, 34.1, 13.0, 23.2 }, -- Highperch
        { 481, 47.9, 41.2, 16.0, 15.0 }, -- Splithoof Crag
        { 485, 32.2, 22.5, 9.5, 10.5 }, -- The Great Lift
        { 483, 30.7, 47.5, 16.5, 24.7 }, -- The Screeching Canyon
        { 439, 78.3, 73.0, 25.0, 48.7 }, -- The Shimmering Flats
        { 2303, 62.4, 55.0, 15.0, 24.7 }, -- Windbreak Canyon
    },
    [1442] = { -- Stonetalon Mountains
        { 2540, 64.9, 92.8, 10.0, 12.0 }, -- Boulderslide Ravine
        { 2538, 77.3, 92.4, 6.0, 5.2 }, -- Camp Aparaje
        { 2537, 75.6, 86.8, 11.5, 7.5 }, -- Grimtotem Post
        { 2539, 72.9, 94.7, 7.0, 8.2 }, -- Malaka'jin
        { 464, 49.2, 40.8, 13.5, 15.7 }, -- Mirkfallon Lake
        { 2541, 54.4, 74.9, 9.0, 10.5 }, -- Sishir Canyon
        { 467, 37.2, 13.5, 20.5, 18.0 }, -- Stonetalon Peak
        { 460, 46.4, 58.4, 11.0, 13.5 }, -- Sun Rock Retreat
        { 465, 31.9, 67.0, 15.0, 21.7 }, -- The Charred Vale
        { 1076, 60.4, 68.5, 21.0, 42.7 }, -- Webwinder Path
        { 461, 69.9, 50.5, 25.9, 29.2 }, -- Windshear Crag
    },
    [1443] = { -- Desolace
        { 2405, 40.9, 30.7, 13.0, 21.0 }, -- Ethel Rethor
        { 606, 38.4, 89.1, 13.0, 16.5 }, -- Gelkis Village
        { 596, 50.6, 58.0, 14.5, 18.7 }, -- Kodo Graveyard
        { 609, 74.4, 48.7, 10.0, 15.0 }, -- Kolkar Village
        { 2407, 64.4, 40.4, 11.0, 12.0 }, -- Kormek's Hut
        { 604, 71.1, 73.0, 12.5, 18.7 }, -- Magram Village
        { 602, 53.4, 79.3, 16.0, 18.0 }, -- Mannoroc Coven
        { 608, 64.9, 9.4, 10.0, 11.2 }, -- Nijel's Point
        { 2406, 28.9, 8.2, 7.0, 9.0 }, -- Ranazjar Isle
        { 603, 75.8, 22.8, 13.0, 17.2 }, -- Sargeron
        { 2198, 80.3, 79.3, 9.0, 13.5 }, -- Shadowbreak Ravine
        { 2408, 25.4, 70.4, 12.0, 15.0 }, -- Shadowprey Village
        { 2404, 54.4, 12.4, 10.0, 9.7 }, -- Tethris Aran
        { 599, 54.4, 28.1, 11.0, 11.2 }, -- Thunder Axe Fortress
        { 607, 33.2, 52.0, 16.5, 27.7 }, -- Valley of Spears
    },
    [1444] = { -- Feralas
        { 1099, 75.3, 42.3, 8.0, 9.7 }, -- Camp Mojache
        { 2577, 58.9, 41.9, 13.0, 13.5 }, -- Dire Maul
        { 1111, 51.4, 10.1, 5.0, 8.2 }, -- Dream Bough
        { 1105, 54.4, 56.9, 7.0, 9.0 }, -- Feral Scar Vale
        { 1106, 53.6, 71.1, 6.5, 18.0 }, -- Frayfeather Highlands
        { 1103, 77.3, 31.1, 10.0, 9.7 }, -- Gordunni Outpost
        { 1100, 67.9, 40.4, 6.0, 15.0 }, -- Grimtotem Compound
        { 1121, 29.7, 79.0, 14.5, 35.2 }, -- Isle of Dread
        { 1137, 86.1, 43.0, 12.5, 14.2 }, -- Lower Wilds
        { 1113, 54.6, 16.8, 5.5, 5.2 }, -- Oneiros
        { 2522, 61.4, 67.0, 10.0, 21.7 }, -- Ruins of Isildien
        { 1114, 39.7, 10.9, 7.5, 8.2 }, -- Ruins of Ravenwind
        { 1120, 30.2, 50.1, 13.5, 16.5 }, -- Sardor Isle
        { 1108, 46.4, 62.1, 7.0, 41.9 }, -- The Forgotten Coast
        { 1119, 47.2, 25.4, 15.5, 21.0 }, -- The Twin Colossals
        { 1101, 72.9, 61.0, 17.0, 20.2 }, -- The Writhing Deep
    },
    [1445] = { -- Dustwallow Marsh
        { 2079, 75.6, 17.6, 12.5, 18.7 }, -- Alcaz Island
        { 496, 36.9, 22.8, 13.0, 24.7 }, -- Brackenwall Village
        { 509, 36.9, 61.4, 11.0, 19.5 }, -- The Den of Flame
        { 2302, 44.4, 48.7, 25.0, 25.4 }, -- The Quagmire
        { 513, 68.1, 51.3, 13.5, 18.7 }, -- Theramore Isle
        { 502, 53.9, 22.8, 19.0, 27.7 }, -- Witch Hill
        { 511, 52.6, 75.2, 17.5, 20.2 }, -- Wyrmbog
    },
    [1446] = { -- Tanaris
        { 1939, 45.7, 42.7, 9.5, 13.5 }, -- Abyssal Sands
        { 1938, 53.1, 45.7, 6.5, 9.0 }, -- Broken Pillar
        { 2300, 64.1, 49.4, 9.5, 10.5 }, -- Caverns of Time
        { 983, 41.9, 56.1, 8.0, 12.0 }, -- Dunemaul Compound
        { 984, 46.7, 65.1, 6.5, 7.5 }, -- Eastmoon Ruins
        { 976, 51.1, 27.3, 10.5, 12.7 }, -- Gadgetzan
        { 987, 54.9, 91.7, 14.0, 14.2 }, -- Land's End Beach
        { 1336, 71.6, 47.2, 8.5, 18.0 }, -- Lost Rigger Cove
        { 1937, 59.9, 24.7, 6.0, 7.5 }, -- Noonshade Ruins
        { 979, 39.9, 28.4, 7.0, 10.5 }, -- Sandsorrow Watch
        { 1940, 62.4, 59.5, 11.0, 9.7 }, -- Southbreak Shore
        { 992, 40.2, 71.5, 7.5, 9.7 }, -- Southmoon Ruins
        { 977, 66.9, 21.3, 8.0, 9.7 }, -- Steamwheedle Port
        { 981, 54.4, 70.7, 11.0, 17.2 }, -- The Gaping Chasm
        { 982, 34.7, 45.7, 7.5, 15.0 }, -- The Noxious Lair
        { 980, 30.7, 62.5, 12.5, 17.2 }, -- Thistleshrub Valley
        { 990, 36.9, 80.5, 8.0, 14.2 }, -- Valley of the Watchers
        { 985, 59.6, 37.8, 9.5, 12.7 }, -- Waterspring Field
        { 986, 66.9, 33.3, 6.0, 9.7 }, -- Zalashji's Den
        { 978, 37.4, 12.7, 15.0, 18.0 }, -- Zul'Farrak
    },
    [1447] = { -- Azshara
        { 1227, 58.9, 54.6, 17.0, 32.9 }, -- Bay of Storms
        { 2497, 76.6, 19.5, 16.5, 15.0 }, -- Bitter Reaches
        { 1233, 29.4, 71.5, 15.0, 15.7 }, -- Forlorn Ridge
        { 1236, 20.7, 60.3, 8.5, 9.7 }, -- Haldarr Encampment
        { 1230, 63.9, 11.2, 47.9, 12.0 }, -- Jagged Reef
        { 1234, 43.2, 80.1, 11.5, 13.5 }, -- Lake Mennar
        { 1219, 57.9, 18.0, 17.0, 9.0 }, -- Legashi Encampment
        { 1232, 70.6, 85.0, 9.5, 9.7 }, -- Ravencrest Monument
        { 1221, 36.7, 54.3, 12.5, 15.7 }, -- Ruins of Eldarath
        { 1235, 17.5, 74.9, 10.0, 13.5 }, -- Shadowsong Shrine
        { 1231, 58.4, 71.9, 28.9, 18.0 }, -- Southridge Beach
        { 1226, 76.6, 41.2, 10.5, 15.0 }, -- Temple of Arkkoran
        { 1220, 60.9, 28.8, 15.0, 9.7 }, -- Thalassian Base Camp
        { 1256, 58.1, 91.7, 28.4, 9.7 }, -- The Ruined Reaches
        { 1228, 45.7, 46.0, 5.5, 18.7 }, -- The Shattered Strand
        { 1229, 88.3, 30.3, 7.0, 12.7 }, -- Tower of Eldara
        { 1225, 46.9, 28.4, 8.0, 12.0 }, -- Ursolan
        { 1237, 21.5, 50.5, 10.0, 8.2 }, -- Valormok
    },
    [1448] = { -- Felwood
        { 1765, 42.4, 48.7, 13.0, 9.0 }, -- Bloodvenom Falls
        { 1761, 49.2, 91.3, 8.5, 9.0 }, -- Deadwood Village
        { 2479, 51.6, 79.7, 9.5, 8.2 }, -- Emerald Sanctuary
        { 1762, 63.4, 10.9, 10.0, 11.2 }, -- Felpaw Village
        { 1767, 50.1, 23.6, 9.5, 11.2 }, -- Irontree Woods
        { 2480, 41.2, 82.7, 8.5, 12.7 }, -- Jadefire Glen
        { 2618, 41.2, 18.0, 8.5, 10.5 }, -- Jadefire Run
        { 1763, 36.4, 59.9, 13.0, 7.5 }, -- Jaedenar
        { 2478, 57.6, 87.9, 7.5, 8.2 }, -- Morlos'Aran
        { 2481, 37.9, 69.2, 9.0, 11.2 }, -- Ruins of Constellas
        { 1766, 42.2, 35.2, 10.5, 18.0 }, -- Shatter Scar Vale
        { 1998, 62.1, 24.3, 7.5, 9.7 }, -- Talonbranch Glade 
    },
    [1449] = { -- Un'Goro Crater
        { 537, 50.4, 49.8, 18.0, 24.7 }, -- Fire Plume Ridge
        { 543, 30.2, 50.1, 17.5, 29.9 }, -- Golakka Hot Springs
        { 1943, 72.4, 34.8, 20.0, 26.2 }, -- Ironstone Plateau
        { 538, 50.6, 20.6, 30.4, 33.7 }, -- Lakkari Tar Pits
        { 539, 37.2, 74.1, 14.5, 24.0 }, -- Terror Run
        { 1942, 69.6, 63.2, 16.5, 35.2 }, -- The Marshlands
        { 540, 51.6, 80.1, 15.5, 19.5 }, -- The Slithering Scar
    },
    [1451] = { -- Silithus
        { 2742, 44.9, 24.3, 13.0, 18.7 }, -- Hive'Ashi
        { 2744, 57.1, 80.5, 16.5, 33.7 }, -- Hive'Regal
        { 2743, 24.7, 58.4, 16.5, 24.0 }, -- Hive'Zora
        { 2738, 62.4, 53.1, 8.0, 12.0 }, -- Southwind Village
        { 2740, 23.2, 17.6, 16.5, 20.2 }, -- The Crystal Vale
        { 2737, 28.9, 95.1, 14.0, 6.0 }, -- The Scarab Wall
    },
    [1452] = { -- Winterspring
        { 2256, 57.9, 83.1, 18.0, 16.5 }, -- Darkwhisper Gorge
        { 2255, 60.9, 37.8, 9.0, 9.7 }, -- Everlook
        { 2246, 33.4, 36.7, 12.0, 7.5 }, -- Frostfire Hot Springs
        { 2241, 49.4, 12.7, 11.0, 9.0 }, -- Frostsaber Rock
        { 2249, 61.9, 68.5, 9.0, 11.2 }, -- Frostwhisper Gorge
        { 2247, 68.1, 45.7, 6.5, 12.0 }, -- Ice Thistle Hills
        { 2251, 53.1, 43.4, 9.5, 12.0 }, -- Lake Kel'Theril
        { 2245, 58.4, 58.0, 6.0, 8.2 }, -- Mazthoril
        { 2250, 65.4, 61.8, 7.0, 9.7 }, -- Owl Wing Thicket
        { 2253, 49.7, 28.4, 10.5, 9.0 }, -- Starfall Village
        { 2242, 64.6, 17.2, 9.5, 10.5 }, -- The Hidden Grove
        { 2243, 40.2, 43.4, 7.5, 6.0 }, -- Timbermaw Post
        { 2244, 68.4, 36.7, 7.0, 7.5 }, -- Winterfall Village
    },
    [1459] = { -- Alterac Valley
        { 2959, 41.9, 20.6, 28.9, 26.2 }, -- Dun Baldar
        { 2978, 51.9, 78.2, 17.0, 29.2 }, -- Frostwolf Keep
        { 2977, 48.9, 49.4, 22.0, 29.9 }, -- Iceblood Garrison
    },
    [2482] = { -- Mount Hyjal
        { 17145, 33.8, 42.3, 14.3, 16.6 }, -- Cradle of Tranquility
        { 16866, 54.4, 37.3, 18.9, 23.7 }, -- Dae'gun
        { 16848, 13.9, 49.9, 11.8, 20.1 }, -- Elderwild
        { 17050, 46.2, 76.8, 15.1, 21.9 }, -- Felblood Scar
        { 17144, 28.8, 70.6, 16.4, 14.5 }, -- Malorne's Retreat
        { 16868, 24.2, 52.7, 10.2, 15.6 }, -- Mourning's Rest
        { 16867, 50.6, 59.1, 14.1, 12.0 }, -- Shrine of Aviana
        { 16849, 78.4, 35.2, 21.8, 32.9 }, -- Summit of Eternity
        { 16853, 70.6, 73.0, 23.0, 25.0 }, -- Tainted Foothills
    },
    [2521] = { -- Zephras Isle
        { 17675, 70.0, 67.1, 6.8, 5.5 }, -- East Pylon Watchtower
        { 17684, 54.0, 81.2, 4.0, 5.2 }, -- Fairweather Stables
        { 16636, 49.9, 54.9, 7.7, 8.7 }, -- Falaath Village
        { 16626, 60.0, 66.6, 12.5, 8.4 }, -- Gustberry Lowlands
        { 17677, 48.1, 69.1, 4.1, 5.5 }, -- Overlook Standing Stones
        { 16630, 71.1, 49.6, 5.2, 11.4 }, -- Rohashi Spires
        { 16833, 58.0, 28.3, 6.7, 15.9 }, -- Ruins of Ban'aethal
        { 16631, 60.3, 38.8, 12.5, 6.1 }, -- Shadowgale Forest
        { 16623, 49.2, 62.0, 11.5, 6.3 }, -- Shen'dar Highlands
        { 16623, 36.8, 50.3, 7.1, 17.4 }, -- Shen'dar Highlands
        { 16624, 44.5, 44.6, 8.3, 7.5 }, -- Shen'dar Village
        { 16629, 62.3, 50.3, 11.6, 11.4 }, -- Shrine of Akir
        { 16622, 41.1, 29.6, 14.6, 6.1 }, -- Thendal Grove
        { 17678, 48.8, 18.6, 4.8, 5.8 }, -- Thendal Standing Stones
        { 16635, 42.8, 22.0, 5.2, 8.7 }, -- Thendal Village
        { 16638, 62.7, 78.7, 13.0, 16.0 }, -- Valanaar
        { 17674, 40.6, 64.0, 5.0, 6.7 }, -- West Pylon Watchtower
        { 16663, 46.8, 82.0, 6.7, 7.9 }, -- Windfield Orchard
        { 16625, 51.8, 47.3, 8.6, 7.5 }, -- Windsong Lake
        { 17676, 45.8, 38.8, 4.9, 5.1 }, -- Windsong Standing Stones
    },
    [2548] = { -- Riverglades
        { 16726, 65.7, 16.4, 13.0, 17.2 }, -- Bolder'ok
        { 16737, 27.3, 62.6, 15.3, 17.1 }, -- Bristle Hills
        { 16734, 52.3, 45.5, 5.4, 9.3 }, -- Elbrim's Farm
        { 16724, 64.8, 82.9, 11.0, 12.0 }, -- Farholde Keep
        { 17780, 44.4, 26.5, 16.8, 20.1 }, -- Krol'dok Stronghold
        { 16735, 44.8, 81.0, 8.0, 8.4 }, -- Meadowsbrook
        { 16727, 76.5, 51.8, 13.2, 11.1 }, -- Powderfuse Port
        { 16743, 58.7, 46.0, 7.7, 8.5 }, -- Rog'mar
        { 16723, 46.1, 51.3, 7.1, 16.3 }, -- Sunnyglade
        { 16729, 60.0, 64.3, 5.9, 6.7 }, -- Terral's Watch
        { 16736, 38.1, 61.0, 7.3, 10.9 }, -- Turner's Logging Camp
        { 16685, 27.5, 43.9, 11.4, 16.0 }, -- Twilight's Shroud
        { 16725, 54.2, 77.6, 8.9, 10.6 }, -- Wheeler's Grange
        { 16731, 76.2, 34.2, 11.3, 17.5 }, -- Windstead
    },
}
